export const siteConfig = {
  name: 'Pixo AI',
  tagline: 'Autonomous Brand Operating System',
  description:
    'The autonomous brand operating system for personal and enterprise use. Pixo agents learn your voice, find opportunities, and deliver ready content daily.',
  url: 'https://www.trypixo.com',
  locale: 'en_US',
  twitter: {
    handle: '@pixoai',
    site: '@pixoai',
    cardType: 'summary_large_image' as const,
  },
  creator: 'Pixo',
  keywords: [
    'autonomous brand operating system',
    'brand operating system',
    'personal branding platform',
    'enterprise brand management',
    'AI brand agents',
    'content automation',
    'professional branding',
    'team branding platform',
    'executive branding',
    'personal branding',
    'linkedin growth',
    'thought leadership',
    'content creation',
    'social media automation',
    'founder branding',
    'ceo branding',
    'executive presence',
    'digital reputation',
    'personal brand strategy',
    'automated content calendar',
    'linkedin scheduling',
    'ghostwriting AI',
    'brand voice',
    'social selling',
    'employee advocacy',
  ],
  authors: [{ name: 'Pixo', url: 'https://www.trypixo.com' }],
  ogImage: '/og-default.png',
  twitterImage: '/og-default.png',
  themeColor: '#0891B2',
  links: {
    // twitter: 'https://twitter.com/pixoai',
    linkedin: 'https://www.linkedin.com/company/pixo-ai-ltd/',
  },
};

export type SiteConfig = typeof siteConfig;
