"""add_template_type_and_carousel_fields

Revision ID: 31aa715769e1
Revises: 993220e87a71
Create Date: 2026-01-26 15:39:40.663581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31aa715769e1'
down_revision: Union[str, None] = '993220e87a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_versions', sa.Column('slides_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('template_versions', sa.Column('slide_count', sa.Integer(), nullable=False))
    op.add_column('templates', sa.Column('template_type', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('slide_count', sa.Integer(), nullable=False))
    op.add_column('templates', sa.Column('extracted_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('templates', sa.Column('extracted_fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('templates', sa.Column('source_file_url', sa.String(length=500), nullable=True))
    op.add_column('templates', sa.Column('slides_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'slides_schema')
    op.drop_column('templates', 'source_file_url')
    op.drop_column('templates', 'extracted_fonts')
    op.drop_column('templates', 'extracted_colors')
    op.drop_column('templates', 'slide_count')
    op.drop_column('templates', 'template_type')
    op.drop_column('template_versions', 'slide_count')
    op.drop_column('template_versions', 'slides_schema')
    # ### end Alembic commands ###
