"""Add template admin fields and version tables

Revision ID: 86d8c66a1b9c
Revises: 
Create Date: 2026-01-21 19:09:29.799662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d8c66a1b9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('industry', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('platform', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('objective', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('format_type', sa.String(length=50), nullable=False))
    op.add_column('templates', sa.Column('layout_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('templates', sa.Column('motion_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('templates', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('templates', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('templates', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('templates', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('templates', sa.Column('dummy_render_passed', sa.Boolean(), nullable=False))
    op.add_column('templates', sa.Column('dummy_render_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'templates', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'dummy_render_url')
    op.drop_column('templates', 'dummy_render_passed')
    op.drop_column('templates', 'approved_at')
    op.drop_column('templates', 'approved_by')
    op.drop_column('templates', 'created_by')
    op.drop_column('templates', 'version')
    op.drop_column('templates', 'motion_schema')
    op.drop_column('templates', 'layout_schema')
    op.drop_column('templates', 'format_type')
    op.drop_column('templates', 'objective')
    op.drop_column('templates', 'platform')
    op.drop_column('templates', 'industry')
    op.drop_column('templates', 'status')
    # ### end Alembic commands ###
