"""Predefined constants for template metadata to ensure consistency."""

# Predefined use cases - these are the standard scenarios when templates should be used
ALLOWED_USE_CASES = [
    "debunking industry misconceptions",
    "educational content about best practices",
    "sharing personal experiences and lessons",
    "providing actionable tips and advice",
    "explaining frameworks and methodologies",
    "challenging conventional wisdom",
    "announcing news and updates",
    "comparing different approaches or tools",
    "telling engaging stories",
    "asking thought-provoking questions",
    "presenting case studies and examples",
    "building thought leadership",
    "establishing expertise in a niche",
    "engaging with trending topics",
    "responding to industry events",
    "sharing behind-the-scenes insights",
    "providing quick wins and hacks",
    "explaining complex concepts simply",
    "motivating and inspiring audience",
    "creating controversy and discussion",
]

# Predefined tags - common topic tags for content categorization
ALLOWED_TAGS = [
    "leadership",
    "productivity",
    "career",
    "entrepreneurship",
    "startups",
    "technology",
    "innovation",
    "business",
    "marketing",
    "sales",
    "strategy",
    "management",
    "product",
    "design",
    "development",
    "data",
    "analytics",
    "ai",
    "automation",
    "remote-work",
    "team-building",
    "culture",
    "growth",
    "fundraising",
    "investing",
    "finance",
    "consulting",
    "coaching",
    "personal-branding",
    "networking",
    "communication",
    "public-speaking",
    "writing",
    "content-creation",
    "social-media",
    "linkedin",
    "twitter",
    "thought-leadership",
    "expertise",
    "industry-insights",
]

# Predefined tone options - these are already constrained in the prompt
ALLOWED_TONES = [
    "professional",
    "casual",
    "authoritative",
    "educational",
    "inspirational",
    "conversational",
    "provocative",
    "empathetic",
    "humorous",
    "technical",
]
