"""Add identity graph onboarding fields

Revision ID: 2509eeaf7f43
Revises: 1a07b5edd64d
Create Date: 2026-01-28 21:51:26.368939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2509eeaf7f43'
down_revision: Union[str, None] = '1a07b5edd64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_graphs', sa.Column('current_role', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('expertise_areas', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Main areas of expertise'))
    op.add_column('identity_graphs', sa.Column('career_highlights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Key career achievements'))
    op.add_column('identity_graphs', sa.Column('career_stage', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('target_audience', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('desired_positioning', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('unique_angles', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Unique perspectives or angles'))
    op.add_column('identity_graphs', sa.Column('aspirations', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('goals', sa.String(), nullable=True))
    op.add_column('identity_graphs', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Personal interests/hobbies'))
    op.add_column('identity_graphs', sa.Column('beliefs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Core beliefs or contrarian views'))
    op.add_column('identity_graphs', sa.Column('contrarian_views', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Contrarian views (legacy field support)'))
    op.add_column('identity_graphs', sa.Column('content_pillars', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Derived content pillars'))
    op.add_column('identity_graphs', sa.Column('onboarding_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Transient state for onboarding conversation'))
    op.add_column('identity_graphs', sa.Column('completeness_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_graphs', 'completeness_score')
    op.drop_column('identity_graphs', 'onboarding_context')
    op.drop_column('identity_graphs', 'content_pillars')
    op.drop_column('identity_graphs', 'contrarian_views')
    op.drop_column('identity_graphs', 'beliefs')
    op.drop_column('identity_graphs', 'interests')
    op.drop_column('identity_graphs', 'goals')
    op.drop_column('identity_graphs', 'aspirations')
    op.drop_column('identity_graphs', 'unique_angles')
    op.drop_column('identity_graphs', 'desired_positioning')
    op.drop_column('identity_graphs', 'target_audience')
    op.drop_column('identity_graphs', 'career_stage')
    op.drop_column('identity_graphs', 'career_highlights')
    op.drop_column('identity_graphs', 'expertise_areas')
    op.drop_column('identity_graphs', 'industry')
    op.drop_column('identity_graphs', 'current_role')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
