"""add_timeline_models

Revision ID: fc832e18ca42
Revises: b9c4d8e7f6a5
Create Date: 2026-02-04 20:15:04.658101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc832e18ca42'
down_revision: Union[str, None] = 'b9c4d8e7f6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_graph_id', sa.UUID(), nullable=False),
    sa.Column('primary_focus', sa.Text(), nullable=True, comment='What the user primarily wants to speak about'),
    sa.Column('narrative_arc', sa.Text(), nullable=True, comment='LLM-synthesized story arc'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_graph_id'], ['identity_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_graph_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('education', 'work', 'usage', 'achievement', 'failure', 'life_event', 'pivot', 'other', name='timeline_event_type'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('emotional_core', sa.Text(), nullable=True, comment='Why this matters/How it felt'),
    sa.Column('lessons_learned', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of specific lessons'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Skills or themes involved'),
    sa.Column('source', sa.String(), nullable=True, comment='Where this came from (linkedin, chat)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_timeline_id'), 'timeline_events', ['timeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_timeline_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('timelines')
    # ### end Alembic commands ###
