import asyncio
import sys
import os
from uuid import UUID

# Add the project root to sys.path
sys.path.append(os.getcwd())

from sqlalchemy import text
from app.core.database import async_session_maker

async def check_agency_drafts_and_profiles():
    async with async_session_maker() as db:
        print("Checking drafts generated by content_agency:")
        try:
            # Check raw SQL first to bypass any enum issues
            result = await db.execute(text("SELECT id, status, generated_by, created_at, profile_id FROM drafts WHERE generated_by = 'content_agency' ORDER BY created_at DESC LIMIT 5"))
            drafts = result.fetchall()
            
            if not drafts:
                print("No drafts found generated by 'content_agency'.")
            else:
                for row in drafts:
                    print(f"  ID: {row.id}, Status: {row.status}, Generated By: {row.generated_by}, Created At: {row.created_at}, Profile ID: {row.profile_id}")

            print("\nChecking Profiles:")
            result = await db.execute(text("SELECT id, name, user_id FROM profiles"))
            for row in result:
                print(f"  Profile ID: {row.id}, Name: {row.name}, User ID: {row.user_id}")

        except Exception as e:
            print(f"  Error checking drafts: {e}")

if __name__ == "__main__":
    asyncio.run(check_agency_drafts_and_profiles())
