'use client';

import { useEffect, useState } from 'react';
import { useProfileStore } from '@/stores/profile-store';
import {
  analyticsApi,
  AnalyticsSummary,
  TopicAnalytics,
  FormatAnalytics,
} from '@/lib/api/analytics';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Select } from '@/components/ui/select';
import { useToast } from '@/components/ui/use-toast';
import { StatCard } from '@/components/analytics/stat-card';
import { BarChart } from '@/components/analytics/bar-chart';
import { DonutChart } from '@/components/analytics/donut-chart';
import {
  BarChart3,
  FileText,
  ThumbsUp,
  ThumbsDown,
  Send,
  Sparkles,
  RefreshCw,
  TrendingUp,
} from 'lucide-react';

const periods = [
  { value: '7d', label: 'Last 7 days' },
  { value: '30d', label: 'Last 30 days' },
  { value: '90d', label: 'Last 90 days' },
];

export default function AnalyticsPage() {
  const { currentProfile } = useProfileStore();
  const { toast } = useToast();

  const [period, setPeriod] = useState('30d');
  const [isLoading, setIsLoading] = useState(true);
  const [summary, setSummary] = useState<AnalyticsSummary | null>(null);
  const [topicsData, setTopicsData] = useState<TopicAnalytics | null>(null);
  const [formatsData, setFormatsData] = useState<FormatAnalytics | null>(null);

  const fetchAnalytics = async () => {
    if (!currentProfile) return;

    setIsLoading(true);
    try {
      const [summaryRes, topicsRes, formatsRes] = await Promise.all([
        analyticsApi.getSummary(currentProfile.id, period),
        analyticsApi.getTopics(currentProfile.id, period),
        analyticsApi.getFormats(currentProfile.id, period),
      ]);

      setSummary(summaryRes);
      setTopicsData(topicsRes);
      setFormatsData(formatsRes);
    } catch (error) {
      toast({
        title: 'Failed to load analytics',
        description: 'Please try again later.',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalytics();
  }, [currentProfile, period]);

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="animate-pulse text-muted-foreground">Loading analytics...</div>
      </div>
    );
  }

  if (!currentProfile) {
    return (
      <div className="flex h-full flex-col items-center justify-center space-y-4">
        <BarChart3 className="h-16 w-16 text-muted-foreground/50" />
        <h2 className="text-xl font-semibold">No profile selected</h2>
        <p className="text-muted-foreground">Create a profile to view analytics.</p>
      </div>
    );
  }

  const donutData = summary
    ? [
        { label: 'Approved', value: summary.drafts_approved, color: 'hsl(142, 76%, 36%)' },
        { label: 'Rejected', value: summary.drafts_rejected, color: 'hsl(0, 84%, 60%)' },
        {
          label: 'Pending',
          value: summary.total_drafts_generated - summary.drafts_approved - summary.drafts_rejected,
          color: 'hsl(217, 91%, 60%)',
        },
      ]
    : [];

  const topicsChartData = topicsData?.topics.map((t) => ({
    label: t.topic || 'Uncategorized',
    value: t.count,
    secondaryValue: t.approval_rate,
  })) || [];

  const formatsChartData = formatsData?.formats.map((f) => ({
    label: f.format,
    value: f.count,
    secondaryValue: f.approval_rate,
  })) || [];

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="flex items-center justify-between border-b bg-card px-6 py-4">
        <div>
          <h1 className="text-2xl font-bold">Analytics</h1>
          <p className="text-sm text-muted-foreground">
            Track your content performance and agent effectiveness
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="w-36"
          >
            {periods.map((p) => (
              <option key={p.value} value={p.value}>
                {p.label}
              </option>
            ))}
          </Select>
          <Button onClick={fetchAnalytics} variant="outline" size="sm">
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6 space-y-6">
        {/* Summary Stats */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <StatCard
            title="Total Drafts"
            value={summary?.total_drafts_generated || 0}
            subtitle="Generated by AI agents"
            icon={FileText}
          />
          <StatCard
            title="Approved"
            value={summary?.drafts_approved || 0}
            subtitle={`${Math.round((summary?.approval_rate || 0) * 100)}% approval rate`}
            icon={ThumbsUp}
          />
          <StatCard
            title="Rejected"
            value={summary?.drafts_rejected || 0}
            icon={ThumbsDown}
          />
          <StatCard
            title="Published"
            value={summary?.drafts_published || 0}
            icon={Send}
          />
        </div>

        {/* Secondary Stats */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader className="pb-2">
              <h3 className="font-semibold flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                Approval Rate
              </h3>
            </CardHeader>
            <CardContent>
              <div className="flex items-end gap-2">
                <span className="text-4xl font-bold">
                  {Math.round((summary?.approval_rate || 0) * 100)}%
                </span>
                <span className="text-muted-foreground mb-1">of drafts approved</span>
              </div>
              <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-muted">
                <div
                  className="h-full rounded-full bg-green-500 transition-all duration-500"
                  style={{ width: `${(summary?.approval_rate || 0) * 100}%` }}
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2">
              <h3 className="font-semibold flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                Average Confidence
              </h3>
            </CardHeader>
            <CardContent>
              <div className="flex items-end gap-2">
                <span className="text-4xl font-bold">
                  {Math.round((summary?.avg_confidence || 0) * 100)}%
                </span>
                <span className="text-muted-foreground mb-1">AI confidence score</span>
              </div>
              <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-muted">
                <div
                  className="h-full rounded-full bg-primary transition-all duration-500"
                  style={{ width: `${(summary?.avg_confidence || 0) * 100}%` }}
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2">
              <h3 className="font-semibold">Draft Status</h3>
            </CardHeader>
            <CardContent>
              <DonutChart
                data={donutData}
                centerValue={String(summary?.total_drafts_generated || 0)}
                centerLabel="Total"
              />
            </CardContent>
          </Card>
        </div>

        {/* Charts */}
        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <h3 className="font-semibold">Performance by Topic</h3>
              <p className="text-sm text-muted-foreground">
                Draft count and approval rate by topic
              </p>
            </CardHeader>
            <CardContent>
              <BarChart
                data={topicsChartData}
                showSecondary
                valueLabel="drafts"
                secondaryLabel="approval"
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <h3 className="font-semibold">Performance by Format</h3>
              <p className="text-sm text-muted-foreground">
                Draft count and approval rate by format
              </p>
            </CardHeader>
            <CardContent>
              <BarChart
                data={formatsChartData}
                showSecondary
                valueLabel="drafts"
                secondaryLabel="approval"
              />
            </CardContent>
          </Card>
        </div>

        {/* Insights */}
        <Card>
          <CardHeader>
            <h3 className="font-semibold">Agent Tuning Suggestions</h3>
            <p className="text-sm text-muted-foreground">
              Based on your approval patterns
            </p>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {(summary?.approval_rate || 0) < 0.5 && (
                <div className="rounded-lg bg-muted/50 p-3">
                  <p className="text-sm">
                    <span className="font-medium">Low approval rate detected.</span>{' '}
                    Consider updating your style preferences or providing more feedback
                    when rejecting drafts to help the AI learn your preferences.
                  </p>
                </div>
              )}
              {topicsData?.topics.some((t) => t.approval_rate < 0.3) && (
                <div className="rounded-lg bg-muted/50 p-3">
                  <p className="text-sm">
                    <span className="font-medium">
                      Some topics have low approval rates.
                    </span>{' '}
                    Consider removing underperforming topics from your preferences or
                    providing more context about how you want them covered.
                  </p>
                </div>
              )}
              {formatsData?.formats.some((f) => f.approval_rate < 0.3) && (
                <div className="rounded-lg bg-muted/50 p-3">
                  <p className="text-sm">
                    <span className="font-medium">
                      Some formats have low approval rates.
                    </span>{' '}
                    Consider adjusting your format preferences in Settings.
                  </p>
                </div>
              )}
              {!summary ||
                ((summary.approval_rate || 0) >= 0.5 &&
                  !topicsData?.topics.some((t) => t.approval_rate < 0.3) &&
                  !formatsData?.formats.some((f) => f.approval_rate < 0.3) && (
                    <div className="rounded-lg bg-green-50 p-3">
                      <p className="text-sm text-green-700">
                        <span className="font-medium">Great job!</span> Your agents are
                        performing well. Keep providing feedback to maintain quality.
                      </p>
                    </div>
                  ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
